package lobo_cine;
import lobo_cine.*;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;

public class AdminUI extends javax.swing.JFrame {
    private Admin admin;
    private BaseDatos db;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminUI.class.getName());

    // Panel con imagen de fondo escalada
    private static class PanelFondo extends JPanel {
        private Image imagen;
        public PanelFondo(LayoutManager layout, Image img) {
            super(layout);
            this.imagen = img;
            setOpaque(false);
        }
        @Override
        protected void paintComponent(Graphics g) {
            if (imagen != null) {
                g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            }
            super.paintComponent(g);
        }
    }

    public AdminUI(Admin a) {
        this.admin = a;
        this.db = BaseDatos.getInstancia();

        // ===== CONFIGURACIÓN =====
        setTitle("Administrador de Lobo Cine");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        Color blanco = Color.WHITE;

        // ===== CARGAR IMAGEN DE FONDO =====
        Image imgFondo = null;
        try {
            imgFondo = ImageIO.read(new File("recursos/Sala_de_cine.jpg"));
        } catch (IOException ex) {
            logger.warning("No se pudo cargar la imagen de fondo: " + ex.getMessage());
        }

        // ===== PANEL PRINCIPAL (con imagen de fondo) =====
        JPanel main = new PanelFondo(new BorderLayout(), imgFondo);
        // Capa semitransparente oscura encima de la imagen para legibilidad
        main.setBackground(new Color(0, 0, 0, 0));

        // ===== TITULO =====
        JLabel titulo = new JLabel("ADMINISTRADOR", SwingConstants.CENTER);
        titulo.setForeground(blanco);
        titulo.setFont(new Font("Arial", Font.BOLD, 32));
        titulo.setBorder(BorderFactory.createEmptyBorder(30,0,30,0));
        titulo.setOpaque(false);

        main.add(titulo, BorderLayout.NORTH);

        // ===== PANEL CENTRAL =====
        JPanel center = new JPanel(new GridBagLayout());
        center.setOpaque(false);

        JPanel panelBotones = new JPanel(new GridLayout(7,1,10,10));
        panelBotones.setOpaque(false);
        panelBotones.setPreferredSize(new Dimension(300, 300));

        JButton btnAgregarPelicula = new JButton("Agregar Película");
        JButton btnAgregarFuncion = new JButton("Agregar Función");
        JButton btnEliminarPelicula = new JButton("Eliminar Película");
        JButton btnEliminarFuncion = new JButton("Eliminar Función");
        JButton btnOcupacion = new JButton("Ver Ocupación");
        JButton btnCrearAdmin = new JButton("Crear Admin");
        JButton btnSalir = new JButton("Salir");

        // estilo botones
        JButton[] botones = {
            btnAgregarPelicula, btnAgregarFuncion, btnEliminarPelicula,
            btnEliminarFuncion, btnOcupacion, btnCrearAdmin, btnSalir
        };

        for (JButton b : botones) {
            b.setBackground(Color.WHITE);
            b.setForeground(Color.BLACK);
            b.setFocusPainted(false);
            b.setFont(new Font("Arial", Font.BOLD, 14));
            panelBotones.add(b);
        }

        center.add(panelBotones);
        main.add(center, BorderLayout.CENTER);

        add(main);

        // ===== SERVICIO =====
        FuncionService funService = new FuncionService(db);

        // ===== EVENTOS =====
        btnAgregarFuncion.addActionListener(e -> {
    dispose();
    new AgregarFuncionUI(admin);
});

        btnAgregarPelicula.addActionListener(e -> {
    dispose();
    new AgregarPeliculaUI(admin);
});

       btnCrearAdmin.addActionListener(e -> {
    dispose();
    new CrearAdminUI(admin);
});

        btnEliminarFuncion.addActionListener(e -> {
    dispose();
    new EliminarFuncionUI(admin);
});

btnEliminarPelicula.addActionListener(e -> {
    dispose();
    new EliminarPeliculaUI(admin);
});

btnOcupacion.addActionListener(e -> {
    dispose();
    new OcupacionUI(admin);
});

        btnSalir.addActionListener(e -> {
            dispose();
            new LoginUI().setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
}