/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lobo_cine;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author jessi
 */
public class AgregarPeliculaUI extends javax.swing.JFrame {
    private Admin admin;
    private BaseDatos db;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarPeliculaUI.class.getName());

    /**
     * Creates new form AgregarPeliculaUI
     */
    public AgregarPeliculaUI(Admin admin) {
         this.admin = admin;
        this.db = BaseDatos.getInstancia();

        setTitle("Agregar Película");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        Color fondo = new Color(25, 50, 90);
        getContentPane().setBackground(fondo);

        // ===== TÍTULO =====
        JLabel titulo = new JLabel("AGREGAR PELÍCULA", SwingConstants.CENTER);
        titulo.setForeground(Color.WHITE);
        titulo.setFont(new Font("Arial", Font.BOLD, 32));
        titulo.setBorder(BorderFactory.createEmptyBorder(40,0,20,0));
        add(titulo, BorderLayout.NORTH);

        // ===== FORM CENTRADO (NO SE TOCA ESTRUCTURA) =====
        JPanel centro = new JPanel(new GridBagLayout());
        centro.setBackground(fondo);

        JPanel form = new JPanel(new GridLayout(5,2,10,15));
        form.setBackground(fondo);

        JTextField txtTitulo = new JTextField();
        JTextField txtDuracion = new JTextField();

        JComboBox<String> comboGenero = new JComboBox<>(
                new String[]{"Acción","Drama","Romance","Animada","Terror"}
        );

        JComboBox<String> comboClas = new JComboBox<>(
                new String[]{"A","B","C"}
        );

        JComboBox<String> comboIdioma = new JComboBox<>(
                new String[]{"Doblada","Subtitulada"}
        );

        JLabel[] labels = {
            new JLabel("Película:"),
            new JLabel("Género:"),
            new JLabel("Duración:"),
            new JLabel("Clasificación:"),
            new JLabel("Idioma:")
        };

        for (JLabel l : labels) {
            l.setForeground(Color.WHITE);
            l.setFont(new Font("Arial", Font.BOLD, 16));
        }

        form.add(labels[0]); form.add(txtTitulo);
        form.add(labels[1]); form.add(comboGenero);
        form.add(labels[2]); form.add(txtDuracion);
        form.add(labels[3]); form.add(comboClas);
        form.add(labels[4]); form.add(comboIdioma);

        centro.add(form);
        add(centro, BorderLayout.CENTER);

        // ===== BOTONES (AQUÍ ESTÁ EL CAMBIO) =====
        JButton btnGuardar = new JButton("Guardar");
        JButton btnRegresar = new JButton("Regresar");

        btnGuardar.setPreferredSize(new Dimension(120, 35));
        btnRegresar.setPreferredSize(new Dimension(120, 35));

        btnGuardar.addActionListener(e -> {
            try {
                String t = txtTitulo.getText();
                String g = comboGenero.getSelectedItem().toString().toLowerCase();
                int d = Integer.parseInt(txtDuracion.getText());
                String c = comboClas.getSelectedItem().toString();
                String i = comboIdioma.getSelectedItem().toString().toLowerCase();

                if (t.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Ingresa el título");
                    return;
                }

                db.getPeliculas().add(new Pelicula(t, g, d, c, i));
                JOptionPane.showMessageDialog(this, "Película agregada");

                txtTitulo.setText("");
                txtDuracion.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Datos inválidos");
            }
        });

        btnRegresar.addActionListener(e -> {
        dispose();
        new AdminUI(admin).setVisible(true);
        });

        JPanel bottom = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 15));
        bottom.setBackground(fondo);

        bottom.add(btnGuardar);
        bottom.add(btnRegresar);

        add(bottom, BorderLayout.SOUTH);

        setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
