/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lobo_cine;
import javax.swing.*;
import java.awt.*;
import java.util.List;

public class CarteleraUI extends javax.swing.JFrame {
    private BaseDatos db;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CarteleraUI.class.getName());

    public CarteleraUI() {
        this.db = BaseDatos.getInstancia();

        // Configuración de la ventana
        setTitle("Cartelera - Lobo Cine");
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Tamaño completo
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        Color fondo = new Color(30, 30, 30); // Consistencia con LoginUI
        getContentPane().setBackground(fondo);

        // Título
        JLabel titulo = new JLabel("CARTELERA DISPONIBLE", SwingConstants.CENTER);
        titulo.setForeground(Color.WHITE);
        titulo.setFont(new Font("Arial", Font.BOLD, 32));
        titulo.setBorder(BorderFactory.createEmptyBorder(30, 0, 30, 0));
        add(titulo, BorderLayout.NORTH);

        // Contenido de la Cartelera
        DefaultListModel<String> modelo = new DefaultListModel<>();
        List<Funcion> funciones = db.getFunciones();

        if (funciones.isEmpty()) {
            modelo.addElement("No hay funciones disponibles en este momento.");
        } else {
            for (Funcion f : funciones) {
                // Información: Película, Género, Clasificación, Sala, Idioma, Horario, Precio [cite: 169]
                String info = String.format(" %s | %s | Clasificación: %s | Sala %d | %s | %s-%s | $%s",
                    f.getPelicula().getTitulo(),
                    f.getPelicula().getGenero(),
                    f.getPelicula().getClasificacion(),
                    f.getSala().getNumero(),
                    f.getPelicula().getIdioma(),
                    f.getHorario(),
                    f.getHoraFinTexto(),
                    f.getPrecio());
                modelo.addElement(info);
            }
        }

        JList<String> lista = new JList<>(modelo);
        lista.setFont(new Font("Arial", Font.PLAIN, 18));
        JScrollPane scroll = new JScrollPane(lista);
        scroll.setBorder(BorderFactory.createEmptyBorder(10, 50, 10, 50));
        add(scroll, BorderLayout.CENTER);

        // Botón Cerrar
        JButton btnCerrar = new JButton("Cerrar");
        btnCerrar.setFont(new Font("Arial", Font.BOLD, 18));
        btnCerrar.addActionListener(e -> dispose());
        
        JPanel panelSur = new JPanel();
        panelSur.setBackground(fondo);
        panelSur.add(btnCerrar);
        add(panelSur, BorderLayout.SOUTH);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CarteleraUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
