/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lobo_cine;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author jessi
 */
public class ClienteUI extends javax.swing.JFrame {
    private Cliente cliente;
    private BaseDatos db;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteUI.class.getName());

    /**
     * Creates new form ClienteUI
     */
    public ClienteUI(Cliente c) {
        this.cliente = c;
        this.db = BaseDatos.getInstancia();

        // ===== CONFIG =====
        setTitle("Cliente - Lobo Cine");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        Color fondo = new Color(0, 102, 204); // azul
        Color blanco = Color.WHITE;

        // ===== PANEL PRINCIPAL =====
        JPanel main = new JPanel(new BorderLayout());
        main.setBackground(fondo);

        // ===== TITULO =====
        JLabel titulo = new JLabel("CLIENTE", SwingConstants.CENTER);
        titulo.setForeground(blanco);
        titulo.setFont(new Font("Arial", Font.BOLD, 32));
        titulo.setBorder(BorderFactory.createEmptyBorder(30,0,30,0));

        main.add(titulo, BorderLayout.NORTH);

        // ===== INFO USUARIO =====
        JPanel top = new JPanel(new GridLayout(3,1));
        top.setBackground(fondo);

        JLabel lblNombre = new JLabel("Nombre: " + cliente.getNombre());
        JLabel lblNumero = new JLabel("Número: " + cliente.getNumero());

        String correo = "";
        for (UsuarioSistema u : db.getUsuarios()) {
            if (u.getPersona() == cliente) {
                correo = u.getCorreo();
                break;
            }
        }

        JLabel lblCorreo = new JLabel("Correo: " + correo);

        JLabel[] labels = {lblNombre, lblNumero, lblCorreo};

        for (JLabel l : labels) {
            l.setForeground(blanco);
            l.setFont(new Font("Arial", Font.BOLD, 16));
        }

        top.add(lblNombre);
        top.add(lblNumero);
        top.add(lblCorreo);

        main.add(top, BorderLayout.WEST);

        // ===== BOTONES =====
        JPanel center = new JPanel(new GridBagLayout());
        center.setBackground(fondo);

        JPanel panelBotones = new JPanel(new GridLayout(5,1,10,10));
        panelBotones.setBackground(fondo);
        panelBotones.setPreferredSize(new Dimension(300, 250));

        JButton btnReservar = new JButton("Reservar");
        JButton btnCancelar = new JButton("Cancelar Reserva");
        JButton btnVer = new JButton("Ver Reservas");
        JButton btnHistorial = new JButton("Historial");
        JButton btnSalir = new JButton("Salir");

        JButton[] botones = {
            btnReservar, btnCancelar, btnVer, btnHistorial, btnSalir
        };

        for (JButton b : botones) {
            b.setBackground(Color.WHITE);
            b.setForeground(Color.BLACK);
            b.setFocusPainted(false);
            b.setFont(new Font("Arial", Font.BOLD, 14));
            panelBotones.add(b);
        }

        center.add(panelBotones);
        main.add(center, BorderLayout.CENTER);

        add(main);

        // ===== EVENTOS =====

        btnReservar.addActionListener(e ->
            new ReservarUI(cliente).setVisible(true)
        );

        btnCancelar.addActionListener(e ->
            new CancelarReservaUI(cliente).setVisible(true)
        );

        btnVer.addActionListener(e ->
            new VerReservasUI(cliente).setVisible(true)
        );

        btnHistorial.addActionListener(e ->
            new HistorialUI(cliente).setVisible(true)
        );

        btnSalir.addActionListener(e -> {
            dispose();
            new LoginUI().setVisible(true);
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
