/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lobo_cine;
import javax.swing.*;
import java.awt.*;
import java.util.List;
/**
 *
 * @author jessi
 */
public class EliminarFuncionUI extends javax.swing.JFrame {
    private Admin admin;
    private BaseDatos db;
    private JList<String> lista;
    private DefaultListModel<String> modelo;
    private List<Funcion> funciones;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EliminarFuncionUI.class.getName());

    /**
     * Creates new form EliminarFuncionUI
     */
    public EliminarFuncionUI(Admin admin) {
        this.admin = admin;
        this.db = BaseDatos.getInstancia();
        this.funciones = db.getFunciones();

        setTitle("Eliminar Función");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        Color fondo = new Color(90, 20, 20);
        getContentPane().setBackground(fondo);

        // ===== PANEL SUPERIOR =====
        JPanel top = new JPanel(new BorderLayout());
        top.setBackground(fondo);

        JButton btnRegresar = new JButton("Regresar");
        btnRegresar.addActionListener(e -> {
            dispose();
            new AdminUI(admin).setVisible(true);
        });

        JLabel titulo = new JLabel("ELIMINAR FUNCIÓN", SwingConstants.CENTER);
        titulo.setForeground(Color.WHITE);
        titulo.setFont(new Font("Arial", Font.BOLD, 28));

        top.add(btnRegresar, BorderLayout.WEST);
        top.add(titulo, BorderLayout.CENTER);

        add(top, BorderLayout.NORTH);

        // ===== LISTA =====
        modelo = new DefaultListModel<>();

        if (funciones.isEmpty()) {
            modelo.addElement("No hay funciones disponibles");
        } else {
            for (Funcion f : funciones) {
                modelo.addElement(
                        f.getPelicula().getTitulo()
                        + " | Sala " + f.getSala().getNumero()
                        + " | " + f.getHorario()
                );
            }
        }

        lista = new JList<>(modelo);
        lista.setFont(new Font("Arial", Font.PLAIN, 18));

        JScrollPane scroll = new JScrollPane(lista);
        add(scroll, BorderLayout.CENTER);

        // ===== BOTÓN ELIMINAR =====
        JButton btnEliminar = new JButton("Eliminar");

        btnEliminar.addActionListener(e -> eliminarFuncion());

        JPanel bottom = new JPanel();
        bottom.setBackground(fondo);
        bottom.add(btnEliminar);

        add(bottom, BorderLayout.SOUTH);

        setVisible(true);
    }

    private void eliminarFuncion() {

    int index = lista.getSelectedIndex();

    if (funciones.isEmpty() || index == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una función");
        return;
    }

    Funcion seleccionada = funciones.get(index);

    int confirmar = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que deseas eliminar esta función?\n\n"
            + seleccionada.getPelicula().getTitulo()
            + "\nSala: " + seleccionada.getSala().getNumero()
            + "\nHora: " + seleccionada.getHorario(),
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
    );

    if (confirmar != JOptionPane.YES_OPTION) return;

    db.getFunciones().remove(index);   // ✅ cambio aquí
    modelo.remove(index);

    if (modelo.isEmpty()) {
        modelo.addElement("No hay funciones disponibles");
    }

    JOptionPane.showMessageDialog(this, "Función eliminada correctamente");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
