package lobo_cine;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author jessi
 */
public class HistorialUI extends javax.swing.JFrame {
    private Cliente cliente;
    private BaseDatos db;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HistorialUI.class.getName());

    /**
     * Creates new form HistorialUI
     */
    public HistorialUI(Cliente c) {
        this.cliente = c;
        this.db = BaseDatos.getInstancia();

        // ===== CONFIG =====
        setTitle("Historial de Reservas");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        Color fondo = new Color(0, 153, 102); // verde
        Color blanco = Color.WHITE;

        // ===== PANEL PRINCIPAL =====
        JPanel main = new JPanel(new BorderLayout());
        main.setBackground(fondo);

        // ===== TITULO =====
        JLabel titulo = new JLabel("HISTORIAL DE RESERVAS", SwingConstants.CENTER);
        titulo.setForeground(blanco);
        titulo.setFont(new Font("Arial", Font.BOLD, 32));
        titulo.setBorder(BorderFactory.createEmptyBorder(30,0,30,0));

        main.add(titulo, BorderLayout.NORTH);

        // ===== LISTA =====
        DefaultListModel<String> modelo = new DefaultListModel<>();
        JList<String> lista = new JList<>(modelo);
        lista.setFont(new Font("Arial", Font.PLAIN, 14));

        JScrollPane scroll = new JScrollPane(lista);
        scroll.setPreferredSize(new Dimension(600, 350));

        // ===== CARGAR DATOS =====
        for (Reserva r : cliente.getHistorial()) {

            String estado = r.isCancelada() ? "Cancelada" : "Activa";

            modelo.addElement(
                r.getFuncion().getPelicula().getTitulo() +
                " | Sala " + r.getFuncion().getSala().getNumero() +
                " | Asiento " + r.getAsiento() +
                " | " + estado
            );
        }

        JPanel center = new JPanel(new GridBagLayout());
        center.setBackground(fondo);
        center.add(scroll);

        main.add(center, BorderLayout.CENTER);

        // ===== BOTÓN =====
        JPanel bottom = new JPanel();
        bottom.setBackground(fondo);

        JButton btnCerrar = new JButton("Cerrar");

        btnCerrar.setBackground(Color.WHITE);
        btnCerrar.setForeground(Color.BLACK);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setFont(new Font("Arial", Font.BOLD, 14));

        bottom.add(btnCerrar);
        main.add(bottom, BorderLayout.SOUTH);

        add(main);

        // ===== EVENTO =====
        btnCerrar.addActionListener(e -> dispose());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
