package lobo_cine;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;
import java.util.List;


/**
 *
 * @author jessi
 */
public class OcupacionUI extends javax.swing.JFrame {
    private Admin admin;
    private BaseDatos db;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OcupacionUI.class.getName());

    // Panel con imagen de fondo escalada
    private static class PanelFondo extends JPanel {
        private Image imagen;
        public PanelFondo(LayoutManager layout, Image img) {
            super(layout);
            this.imagen = img;
            setOpaque(false);
        }
        @Override
        protected void paintComponent(Graphics g) {
            if (imagen != null) {
                g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            }
            super.paintComponent(g);
        }
    }

    /**
     * Creates new form OcupacionUI
     */
    public OcupacionUI(Admin admin) {
        this.admin = admin;
        this.db = BaseDatos.getInstancia();

        setTitle("Ocupación de Funciones");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        // ===== CARGAR IMAGEN DE FONDO =====
        Image imgFondo = null;
        try {
            imgFondo = ImageIO.read(new File("recursos/Sala_de_cine.jpg"));
        } catch (IOException ex) {
            logger.warning("No se pudo cargar la imagen de fondo: " + ex.getMessage());
        }

        // Panel raíz con imagen
        JPanel root = new PanelFondo(new BorderLayout(), imgFondo);
        setContentPane(root);

        // ===== PANEL SUPERIOR =====
        JPanel top = new JPanel(new BorderLayout());
        top.setOpaque(false);

        JButton btnRegresar = new JButton("Regresar");
        btnRegresar.addActionListener(e -> {
            dispose();
            new AdminUI(admin).setVisible(true);
        });

        JLabel titulo = new JLabel("OCUPACIÓN DE FUNCIONES", SwingConstants.CENTER);
        titulo.setForeground(Color.WHITE);
        titulo.setFont(new Font("Arial", Font.BOLD, 28));

        top.add(btnRegresar, BorderLayout.WEST);
        top.add(titulo, BorderLayout.CENTER);

        root.add(top, BorderLayout.NORTH);

        // ===== CONTENIDO =====
        JTextArea area = new JTextArea();
        area.setFont(new Font("Arial", Font.PLAIN, 18));
        area.setEditable(false);
        area.setOpaque(true);
        area.setBackground(new Color(0, 0, 0, 180));
        area.setForeground(Color.WHITE);

        List<Funcion> funciones = db.getFunciones();

        if (funciones.isEmpty()) {
            area.setText("No hay funciones registradas.");
        } else {

            StringBuilder info = new StringBuilder();

            for (Funcion f : funciones) {

                String[] asientos = f.getAsientos();
                int ocupados = 0;

                for (String a : asientos) {
                    if ("O".equals(a)) ocupados++;
                }

                info.append("Película: ").append(f.getPelicula().getTitulo())
                    .append("\nSala: ").append(f.getSala().getNumero())
                    .append("\nHorario: ").append(f.getHorario())
                    .append("\nOcupados: ").append(ocupados)
                    .append("/").append(asientos.length)
                    .append("\n----------------------------------------\n");
            }

            area.setText(info.toString());
        }

        JScrollPane scroll = new JScrollPane(area);
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        root.add(scroll, BorderLayout.CENTER);

        setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}