/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lobo_cine;

import javax.swing.*;
import java.awt.*;


/**
 *
 * @author jessi
 */
public class RegistroUI extends javax.swing.JFrame {
    private BaseDatos db;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroUI.class.getName());

    /**
     * Creates new form RegistroUI
     */
    public RegistroUI() {
        db = BaseDatos.getInstancia();

        // ===== CONFIG =====
        setTitle("Registro de Cliente");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        Color fondo = new Color(153, 0, 0); // rojo vino
        getContentPane().setBackground(fondo);

        // ===== TÍTULO =====
        JLabel titulo = new JLabel("REGISTRO", JLabel.CENTER);
        titulo.setFont(new Font("Arial", Font.BOLD, 30));
        titulo.setForeground(Color.WHITE);
        titulo.setBorder(BorderFactory.createEmptyBorder(30, 10, 20, 10));
        add(titulo, BorderLayout.NORTH);

        // ===== PANEL CENTRAL =====
        JPanel center = new JPanel(new GridBagLayout());
        center.setBackground(fondo);

        JPanel form = new JPanel(new GridBagLayout());
        form.setBackground(fondo);
        form.setPreferredSize(new Dimension(450, 300));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10,10,10,10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // ===== CAMPOS =====
        JTextField txtNombre = new JTextField();
        JTextField txtCorreo = new JTextField();
        JTextField txtPassword = new JTextField();

        txtNombre.setPreferredSize(new Dimension(250, 35));
        txtCorreo.setPreferredSize(new Dimension(250, 35));
        txtPassword.setPreferredSize(new Dimension(250, 35));

        // ===== LABELS =====
        JLabel lblNombre = crearLabel("Nombre:");
        JLabel lblCorreo = crearLabel("Correo:");
        JLabel lblPass = crearLabel("Password:");

        // ===== AGREGAR FORM =====
        gbc.gridx = 0; gbc.gridy = 0;
        form.add(lblNombre, gbc);
        gbc.gridx = 1;
        form.add(txtNombre, gbc);

        gbc.gridx = 0; gbc.gridy = 1;
        form.add(lblCorreo, gbc);
        gbc.gridx = 1;
        form.add(txtCorreo, gbc);

        gbc.gridx = 0; gbc.gridy = 2;
        form.add(lblPass, gbc);
        gbc.gridx = 1;
        form.add(txtPassword, gbc);

        center.add(form);
        add(center, BorderLayout.CENTER);

        // ===== BOTÓN =====
        JPanel bottom = new JPanel();
        bottom.setBackground(fondo);

        JButton btnRegistrar = new JButton("Registrar");
        btnRegistrar.setBackground(Color.WHITE);
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFont(new Font("Arial", Font.BOLD, 20));
        
        JButton btnRegresar = new JButton("Regresar");
        btnRegresar.setBackground(Color.WHITE);
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFont(new Font("Arial", Font.BOLD, 20));

        bottom.add(btnRegistrar);
        bottom.add(btnRegresar);
        add(bottom, BorderLayout.SOUTH);

        // ===== EVENTO =====
        btnRegistrar.addActionListener(e -> {

            String nombre = txtNombre.getText();
            String correo = txtCorreo.getText();
            String password = txtPassword.getText();

            if (nombre.isEmpty() || correo.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Completa todos los campos");
                return;
            }

            for (UsuarioSistema u : db.getUsuarios()) {
                if (u.getCorreo().equalsIgnoreCase(correo)) {
                    JOptionPane.showMessageDialog(this, "Correo ya registrado");
                    return;
                }
            }

            Cliente nuevo = new Cliente(nombre, db.getUsuarios().size());
            db.agregarUsuario(new UsuarioSistema(correo, password, nuevo));

            JOptionPane.showMessageDialog(this, "Cliente registrado correctamente");
            dispose();
        });
        
        btnRegresar.addActionListener(e -> {
        dispose();
        });
    }

    // ===== MÉTODO PARA LABEL =====
    private JLabel crearLabel(String texto) {
        JLabel l = new JLabel(texto);
        l.setForeground(Color.WHITE);
        l.setFont(new Font("Arial", Font.BOLD, 16));
        return l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
