/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lobo_cine;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author jessi
 */
public class VerReservasUI extends javax.swing.JFrame {
    private Cliente cliente;
    private BaseDatos db;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerReservasUI.class.getName());

    /**
     * Creates new form VerReservasUI
     */
    public VerReservasUI(Cliente c) {
         this.cliente = c;
        this.db = BaseDatos.getInstancia();

        // ===== CONFIG GENERAL =====
        setTitle("Reservas Activas - Lobo Cine");
        setExtendedState(JFrame.MAXIMIZED_BOTH); // pantalla completa
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        Color fondo = new Color(30, 50, 90); // color diferente (azul)
        getContentPane().setBackground(fondo);

        // ===== TÍTULO =====
        JLabel titulo = new JLabel("Reservas Activas", JLabel.CENTER);
        titulo.setFont(new Font("Arial", Font.BOLD, 30));
        titulo.setForeground(Color.WHITE);
        titulo.setBorder(BorderFactory.createEmptyBorder(20, 10, 20, 10));

        add(titulo, BorderLayout.NORTH);

        // ===== LISTA =====
        DefaultListModel<String> modelo = new DefaultListModel<>();
        JList<String> lista = new JList<>(modelo);
        lista.setFont(new Font("Arial", Font.PLAIN, 20));
        lista.setBackground(Color.WHITE);

        // ===== CARGAR RESERVAS =====
        for (Reserva r : db.getReservas()) {

            if (r.getCliente() == cliente && !r.isCancelada()) {

                modelo.addElement(
                    "🎬 " + r.getFuncion().getPelicula().getTitulo() +
                    " | Sala " + r.getFuncion().getSala().getNumero() +
                    " | Asiento " + r.getAsiento() +
                    " | " + r.getFuncion().getHorario()
                );
            }
        }

        JScrollPane scroll = new JScrollPane(lista);
        scroll.setBorder(BorderFactory.createEmptyBorder(20, 50, 20, 50));

        add(scroll, BorderLayout.CENTER);

        // ===== BOTÓN =====
        JButton btnCerrar = new JButton("Cerrar");
        btnCerrar.setFont(new Font("Arial", Font.BOLD, 18));
        btnCerrar.setBackground(Color.WHITE);

        JPanel sur = new JPanel();
        sur.setBackground(fondo);
        sur.setBorder(BorderFactory.createEmptyBorder(20, 10, 20, 10));
        sur.add(btnCerrar);

        add(sur, BorderLayout.SOUTH);

        // ===== EVENTO =====
        btnCerrar.addActionListener(e -> dispose());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
